---
version: "3.9"
services:
  sui:
    image: mysten/sui-node:stable
    container_name: sui
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
      - "0.0.0.0:9184:9184"
    expose:
      - "9000"
      - "9001"
      - "9184"
    restart: always
    volumes:
      - ./config.yml:/sui/fullnode.yaml:ro
      - ./genesis.blob:/sui/genesis.blob:ro
      - ./suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  suidb:
